exe: main.cpp Board.cpp Piece.cpp Game.cpp Pawn.cpp Cell.cpp King.cpp Queen.cpp Rook.cpp Bishop.cpp Knight.cpp MoveData.cpp
	g++ -o exe main.cpp Board.cpp Piece.cpp Game.cpp Pawn.cpp Cell.cpp King.cpp Queen.cpp Rook.cpp Bishop.cpp Knight.cpp MoveData.cpp
